with-expecter: true
outpkg: "mocks"
dir: "{{.InterfaceDir}}/mocks/"
mockname: "Fake{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase}}.gen.go"

# Flags for future v3 compatibility.
# See https://github.com/vektra/mockery/issues/848
issue-845-fix: true
resolve-type-alias: false

packages:
  github.com/tbe-team/raybot/internal/config:
    config:
      all: true
  github.com/tbe-team/raybot/internal/controller/picserial/serial:
    config:
      all: true
  github.com/tbe-team/raybot/internal/repository:
    config:
      all: true
  github.com/tbe-team/raybot/internal/service:
    config:
      all: true
