log:
  level: info
  format: text
  add_source: false

hardware:
  esp:
    serial:
      port: /dev/ttyUSB0
      baud_rate: 9600
      data_bits: 8
      stop_bits: 1
      parity: none
      read_timeout: 1s
  pic:
    serial:
      port: /dev/ttyUSB1
      baud_rate: 9600
      data_bits: 8
      stop_bits: 1
      parity: none
      read_timeout: 1s

cloud:
  address: localhost:50051
  token: 4d24e88b41374b34a54806c0124b4052

grpc:
  enable: true
