log:
  level: debug
  format: json
  add_source: false
grpc:
  port: 50051
http:
  port: 8080
  enable_swagger: true
pic:
  serial:
    port: /dev/ttyUSB0
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: none
    read_timeout: 1s
