SystemConfigResponse:
  type: object
  properties:
    log:
      $ref: "#/LogConfig"
      x-order: 1
    grpc:
      $ref: "#/GRPCConfig"
      x-order: 2
    http:
      $ref: "#/HTTPConfig"
      x-order: 3
    pic:
      $ref: "#/PicConfig"
      x-order: 4
    esp:
      $ref: "#/ESPConfig"
      x-order: 5
  required:
    - log
    - grpc
    - http
    - pic
    - esp

SystemConfigRequest:
  type: object
  properties:
    log:
      $ref: "#/LogConfig"
    grpc:
      $ref: "#/GRPCConfig"
    http:
      $ref: "#/HTTPConfig"
    pic:
      $ref: "#/PicConfig"
    esp:
      $ref: "#/ESPConfig"
  required:
    - log
    - grpc
    - http
    - pic
    - esp

GRPCConfig:
  type: object
  properties:
    server:
      $ref: "#/GRPCServerConfig"
    cloud:
      $ref: "#/CloudConfig"
  required:
    - server
    - cloud

GRPCServerConfig:
  type: object
  properties:
    enable:
      type: boolean
      example: true
      description: Whether to enable the gRPC server
      x-order: 1
  required:
    - enable

CloudConfig:
  type: object
  properties:
    address:
      type: string
      example: "localhost:50051"
      description: The address for the cloud service
      x-order: 1
  required:
    - address

HTTPConfig:
  type: object
  properties:
    enableSwagger:
      type: boolean
      example: true
      description: Whether to enable the Swagger UI
      x-order: 1
  required:
    - enableSwagger

LogConfig:
  type: object
  properties:
    level:
      type: string
      enum:
        - debug
        - info
        - warn
        - error
      example: "debug"
      description: The log level for the gRPC server
      x-order: 1
      x-go-type: string
    format:
      type: string
      enum:
        - json
        - text
      example: "json"
      description: The log format for the gRPC server
      x-order: 2
      x-go-type: string
    addSource:
      type: boolean
      example: false
      description: Whether to add the source to the log
      x-order: 3
  required:
    - level
    - format
    - addSource

PicConfig:
  type: object
  properties:
    serial:
      $ref: "#/SerialConfig"
  required:
    - serial

ESPConfig:
  type: object
  properties:
    serial:
      $ref: "#/SerialConfig"
  required:
    - serial

SerialConfig:
  type: object
  properties:
    port:
      type: string
      example: "/dev/ttyUSB0"
      description: The port name for the serial connection
      x-order: 1
    baudRate:
      type: integer
      example: 9600
      description: The baud rate for the serial connection
      x-order: 2
    dataBits:
      type: integer
      example: 8
      description: The data bits for the serial connection
      x-order: 3
    stopBits:
      type: number
      format: double
      example: 1
      description: The stop bits for the serial connection
      x-order: 4
      x-go-type: float64
    parity:
      type: string
      enum:
        - none
        - even
        - odd
      example: "none"
      description: The parity for the serial connection
      x-order: 5
      x-go-type: string
    readTimeout:
      type: number
      format: double
      example: 1
      description: The read timeout for the serial connection
      x-order: 6
      x-go-type: float64
  required:
    - port
    - baudRate
    - dataBits
    - stopBits
    - parity
    - readTimeout
