get:
  summary: Get the HTTP configuration
  operationId: getHTTPConfig
  description: Get the HTTP configuration
  tags:
    - config
  responses:
    "200":
      description: The HTTP configuration
      content:
        application/json:
          schema:
            $ref: "../components/schemas/config.yml#/HTTPConfig"
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "../components/schemas/error.yml#/ErrorResponse"

put:
  summary: Update the HTTP configuration
  operationId: updateHTTPConfig
  description: Update the HTTP configuration
  tags:
    - config
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../components/schemas/config.yml#/HTTPConfig"
  responses:
    "200":
      description: The updated HTTP configuration
      content:
        application/json:
          schema:
            $ref: "../components/schemas/config.yml#/HTTPConfig"
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "../components/schemas/error.yml#/ErrorResponse"
