get:
  summary: Get the gRPC configuration
  operationId: getGRPCConfig
  description: Get the gRPC configuration
  tags:
    - config
  responses:
    "200":
      description: The gRPC configuration
      content:
        application/json:
          schema:
            $ref: "../components/schemas/config.yml#/GRPCConfig"
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "../components/schemas/error.yml#/ErrorResponse"

put:
  summary: Update the gRPC configuration
  operationId: updateGRPCConfig
  description: Update the gRPC configuration
  tags:
    - config
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../components/schemas/config.yml#/GRPCConfig"
  responses:
    "200":
      description: The updated gRPC configuration
      content:
        application/json:
          schema:
            $ref: "../components/schemas/config.yml#/GRPCConfig"
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "../components/schemas/error.yml#/ErrorResponse"
