get:
  summary: Get system configuration
  operationId: getSystemConfig
  description: Get the system configuration
  tags:
    - system
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../components/schemas/system_config.yml#/SystemConfigResponse"
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "../components/schemas/error.yml#/ErrorResponse"

put:
  summary: Update system configuration
  operationId: updateSystemConfig
  description: Update the system configuration
  tags:
    - system
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../components/schemas/system_config.yml#/SystemConfigRequest"
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../components/schemas/system_config.yml#/SystemConfigResponse"
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "../components/schemas/error.yml#/ErrorResponse"
