openapi: 3.0.0
info:
  version: 0.1.0
  title: Raybot API
  description: >-
    The Raybot API
  license:
    url: https://opensource.org/licenses/MIT
    name: MIT
servers:
  - url: /api/v1
security: []
paths:
  /configs/log:
    $ref: "./paths/configs@log.yml"
  /configs/hardware:
    $ref: "./paths/configs@hardware.yml"
  /configs/cloud:
    $ref: "./paths/configs@cloud.yml"
  /configs/grpc:
    $ref: "./paths/configs@grpc.yml"
  /configs/http:
    $ref: "./paths/configs@http.yml"
  /system/restart:
    $ref: "./paths/system@restart.yml"
  /robot-state:
    $ref: "./paths/robot-state.yml"
  # /commands:
  #   $ref: "./paths/commands.yml"
  # /commands/in-progress:
  #   $ref: "./paths/commands@in-progress.yml"
