// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	cloudsession "github.com/tbe-team/raybot/internal/services/cloudsession"

	mock "github.com/stretchr/testify/mock"
)

// FakeService is an autogenerated mock type for the Service type
type FakeService struct {
	mock.Mock
}

type FakeService_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeService) EXPECT() *FakeService_Expecter {
	return &FakeService_Expecter{mock: &_m.Mock}
}

// HeartbeatSession provides a mock function with given fields: ctx, sessionID
func (_m *FakeService) HeartbeatSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for HeartbeatSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FakeService_HeartbeatSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeartbeatSession'
type FakeService_HeartbeatSession_Call struct {
	*mock.Call
}

// HeartbeatSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *FakeService_Expecter) HeartbeatSession(ctx interface{}, sessionID interface{}) *FakeService_HeartbeatSession_Call {
	return &FakeService_HeartbeatSession_Call{Call: _e.mock.On("HeartbeatSession", ctx, sessionID)}
}

func (_c *FakeService_HeartbeatSession_Call) Run(run func(ctx context.Context, sessionID string)) *FakeService_HeartbeatSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FakeService_HeartbeatSession_Call) Return(_a0 error) *FakeService_HeartbeatSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeService_HeartbeatSession_Call) RunAndReturn(run func(context.Context, string) error) *FakeService_HeartbeatSession_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function with given fields: ctx
func (_m *FakeService) StartSession(ctx context.Context) (cloudsession.Session, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 cloudsession.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (cloudsession.Session, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) cloudsession.Session); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(cloudsession.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FakeService_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type FakeService_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FakeService_Expecter) StartSession(ctx interface{}) *FakeService_StartSession_Call {
	return &FakeService_StartSession_Call{Call: _e.mock.On("StartSession", ctx)}
}

func (_c *FakeService_StartSession_Call) Run(run func(ctx context.Context)) *FakeService_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *FakeService_StartSession_Call) Return(_a0 cloudsession.Session, _a1 error) *FakeService_StartSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FakeService_StartSession_Call) RunAndReturn(run func(context.Context) (cloudsession.Session, error)) *FakeService_StartSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeService creates a new instance of FakeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeService {
	mock := &FakeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
