name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          cache: false

      - name: Build standard
        run: make build

      - name: Build ARM64
        run: make build-arm64

      - name: Upload standard binary
        uses: actions/upload-artifact@v4
        with:
          name: raybot
          path: bin/raybot

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: raybot-arm64
          path: bin/raybot-arm64
